name: flutter_favorite_places
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.3
  google_fonts: ^6.2.1
  http: ^1.2.2
  image_picker: ^1.1.2
  location: ^7.0.1
  path: ^1.9.0
  path_provider: ^2.1.4
  sqflite: ^2.4.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
